version: 2
jobs:
  build:
    working_directory: ~/gaps
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build App
          command: npm run build
      - name: Deploy to Firebase
        command: npm run deploy -- --token "$FIREBASE_TOKEN"
